### ISSUE TITLE
Implementing ACE D1S library plotting capability

### ISSUE THREAD

**Issue by Radiation-Transport** [JADE-V-V/JADE#127] opened 2021-10-26 14:37 UTC
As per title

**Comment by dodu94** [comment] 2023-09-28 14:53
@AlbertoBittes this should already work using the utility that you recently added no? it just needs an ACE library and a MT channel

**Comment by dodu94** [comment] 2024-08-08 10:27
duplicate of #203

**Closed** 2024-09-05 12:11 UTC
Labels: enhancement
